### ISSUE TITLE
Generate code schema from metadata

### ISSUE THREAD

**Issue by Diaskhan** [hherzl/CatFactory.EntityFrameworkCore#1]
It possible to generate models,mappings,migrations from MetaData ?

not from Database ?

I have dived in migratiosn of EF core!
Iam Searching tools to generate Class models, and mappings !
Need for Enterpise ))

**Comment by hherzl** [comment]
Hi.

What do you mean with MetaData?

With CatFactory, We can create a representation for Database without importing from SQL Server instance to perform scaffolding.

Example:

```csharp
var db = new Database
{
	Name = "School",
	DefaultSchema = "dbo",
	DatabaseTypeMaps = DatabaseTypeMapList.Definition,
	Tables =
	{
		new Table
		{
			Schema = "dbo",
			Name = "Student",
			Columns =
			{
				new Column { Name = "StudentID", Type = "int" },
				new Column { Name = "FirstName", Type = "nvarchar", Length = 15 },
				new Column { Name = "MiddleName", Type = "nvarchar", Length = 15, Nullable = true },
				new Column { Name = "LastName", Type = "nvarchar", Length = 15 }
			},
			Identity = new Identity("StudentID", 1000, 1000),
			PrimaryKey = new PrimaryKey("StudentID")
		}
	}
};
```

I can add support for MetaData in roadmap, I only need more feedback from your side.

Regards

**Comment by Diaskhan** [comment]
Actually iam aiming to use ef core migration mechanism to create table and fields ! Because is cross database platform !

**Comment by hherzl** [comment]
Hi.

MySQL?
PostgreSQL?
Oracle?

**Comment by Diaskhan** [comment]
Yes!

**Comment by Diaskhan** [comment]
[EntityDesignerUtills.zip](https://github.com/hherzl/CatFactory.EntityFrameworkCore/files/2614738/EntityDesignerUtills.zip)

For example this thing is used for Ef CORE, and working on all database !

**Comment by hherzl** [comment]
Let me check.

Regards

**Comment by Diaskhan** [comment]
I could advice i u to see this repo 
https://github.com/sergey-kolodiy/PolyGen

Its generate ef core models and and other things using roslyn ! 

Crazy russian ))
