### ISSUE TITLE
Generate Entities compatible with C# 8 Nullable Reference Types

### ISSUE THREAD

**Issue by glacasa** [hherzl/CatFactory.EntityFrameworkCore#11]
I would like to enable [nullable reference type](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types) on my project, the only blocker for now are the entities (scaffolded by ef core)

It is possible to work with NRT in EF Core :
https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types

What needs to be added (minimal) whit this option : 
- In DbContext, add `= null!;` in front of each DbSet
- In the entities, each property is either nullable (add ? to the type, like it's already done for struct types today) or not nullable (add `=null!;`).

Let me know how I can help on this (I'm not sure where to start)

**Comment by hherzl** [comment]
The latest version allows to modify types in scaffolding, check the following code: [ScaffoldingEventHandlersTests](https://github.com/hherzl/CatFactory.EntityFrameworkCore/blob/master/CatFactory.EntityFrameworkCore.Tests/ScaffoldingEventHandlersTests.cs)

Take a look on this block:

```csharp
if (args.CodeBuilder.ObjectDefinition is EntityClassDefinition entityDef)
{
	foreach (var prop in entityDef.Properties)
	{
		if (prop.Type == "string")
			prop.Type = "string?";
	}
}
```

**Comment by glacasa** [comment]
Perfect :) I managed to scaffold my entities with no warnings, using this code : 

`
            project.ScaffoldingDefinition += (sender, args) =>
            {
                if (args.CodeBuilder.ObjectDefinition is EntityClassDefinition entityDef)
                {
                    var columns = ((CatFactory.ObjectRelationalMapping.Table)entityDef.DbObject).Columns;
                    foreach (var prop in entityDef.Properties)
                    {
                        var name = prop.Name;
                        var col = columns.FirstOrDefault(c => c.Name == name);

                        if (col?.Nullable == true && !prop.Type.EndsWith("?"))
                        {
                            // Id DB col is Nullable, type should also be nullable
                            prop.Type += "?";
                        }
                        else
                        {
                            // Navigation property : we add null-forgiving init
                            prop.InitializationValue = "default!";
                        }

                    }
                }
                else if (args.CodeBuilder.ObjectDefinition is DbContextClassDefinition dbContextDef)
                {
                    foreach (var prop in dbContextDef.Properties)
                    {
                        prop.InitializationValue = "default!";
                    }
                }
            };
`
