### ISSUE TITLE
Scaffolding for EF Core Versions

### ISSUE THREAD

**Issue by hherzl** [hherzl/CatFactory.EntityFrameworkCore#12]
- [x] Make configurations internals
- [x] Add version for Entity Framework Core Project (enum)
- [ ] Allow customize naming conventions
- [x] Generate **Function Attribute** according EF Core Version
- [x] Generate **Identity** method name according EF Core Version
- [x] Generate **NoKey** method for Views mapping
- [x] Add tests for Scaffolding Event Handlers

**Comment by hherzl** [comment]
This it was solved with [1.0.0-beta-sun-build50](https://www.nuget.org/packages/CatFactory.EntityFrameworkCore/1.0.0-beta-sun-build50) version, please check this version

**Comment by glacasa** [comment]
Works fine ! 👍

You can also add version 5 target.
I don't see breaking changes, scaffolded entities on my database builds without warning with EF Core 5 RC1
