### ISSUE TITLE
Generated DBFunction in DbContext doesn't build with EF Core 3+

### ISSUE THREAD

**Issue by glacasa** [hherzl/CatFactory.EntityFrameworkCore#7]
When scaffolding the DbContext, sql functions are added to the DbContext with the attribute `[DbFunction(FunctionName="TheName", Schema="dbo")]`

https://github.com/hherzl/CatFactory.EntityFrameworkCore/blob/30db13efd618ee42b49a62a081f27eb149a7b79b/CatFactory.EntityFrameworkCore/Definitions/Extensions/DbContextClassBuilder.cs#L125

In version 3.0, the `FunctionName` property was renamed `Name`, and now we can't build the DbContext with updated EF Core

https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.entityframeworkcore.dbfunctionattribute.name?view=efcore-3.1

**Comment by hherzl** [comment]
There must be a fix for EF Core V3, also of this feature CatFactory needs to scaffold in right way another configurations like **Identity** property in EF Core V3.

**Comment by hherzl** [comment]
This it was solved with [1.0.0-beta-sun-build50](https://www.nuget.org/packages/CatFactory.EntityFrameworkCore/1.0.0-beta-sun-build50) version, please check this version

**Comment by glacasa** [comment]
Works well now, perfect ! 👍
